apiVersion: v1
kind: Pod
metadata:
  name: snmp-helper
  namespace: monitoring
spec:
  securityContext:
    runAsUser: 1000  # Menjalankan pod sebagai user 1000
    runAsNonRoot: true  # Memastikan tidak berjalan sebagai root
  containers:
  - name: snmp-helper
    image: hiroominan/ubuntu:snmp
    command: ["/bin/sh", "-c", "sleep infinity"]  # Agar tetap berjalan
    securityContext:
      allowPrivilegeEscalation: true  # Mencegah eskalasi privilege
      runAsUser: 1000  # Menjalankan container sebagai user 1000
