scrape_configs:
  - job_name: idrac
    http_sd_configs:
      - url: http://idrac-exporter.monitoring.svc.cluster.local:9348/discover
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - source_labels: [__meta_url]
        target_label: __address__
        regex: (https?.{3})([^\/]+)(.+)
        replacement: $2
